### ISSUE TITLE
SA0001 after updating to Mono 4.0.1

### ISSUE THREAD

**Issue by Altorffer** [DarkCloud14/MonoDevelop.StyleCop#12]
Last night I updated to Mono 4.0.1 and from that moment on, StyleCop has been throwing SA0001 on the first file in my project it tries to analyze.

Specifically, "SA0001: CoreParser: An exception occurred while parsing the file: System.TypeLoadException, A type load exception has occurred."

Same with simply starting a whole new (dummy) project.

Step 1: Close any and all workspaces.
Step 2: CTRL+SHIFT+N to start a new solution.
Step 3: Run StyleCop. Result: SA0001, typeloadexception.

**Comment by DarkCloud14** [comment]
Which OS do you use? OS X if so did you compile it yourself or do you have a link to an official package? Couldn't find one on official mono-project.com site as they still offer 3.12.1 there for OS X.

If you're running Linux which distribution and did you use an official or third party repository to download it or did you compile it from source?!

**Comment by Altorffer** [comment]
Linux, Xubuntu 15.04, kernel version 4.1.rc1. Mono 4.0.1 was installed from the official repositories as per http://www.mono-project.com/docs/getting-started/install/linux/

**Comment by DarkCloud14** [comment]
OK I'll test it asap with the same system but I cannot guarantee that I can fix it, in worst case it's a bug in Mono 4.0.1 which produces the problem..

**Comment by Altorffer** [comment]
Thanks for looking at it at least. Although I am certain that once you have updated StyleCop to MonoDevelop 5.9 (which has now also been released), the issue will have resolved itself. Since I do agree with you, some form of inconsistency/incompatibility as a result of Mono 4.0.1 (which adopted C# 6.0, for one thing).

**Comment by DarkCloud14** [comment]
Ok I guess the problem is, that the official StyleCop build is done using .Net 2.0/.Net 3.5 and as Mono 4.0 and later dropped support for these I must test if rebuilding StyleCop with .Net 4.0/.Net 4.5 will work be enough.

**Comment by Altorffer** [comment]
Specifically, 4.5. Everything below 4.5 was dropped. For reference, see http://www.mono-project.com/docs/about-mono/releases/4.0.0/

**Comment by DarkCloud14** [comment]
Sorry you're right so I'll test with .Net 4.5.

**Comment by MazZilaaaa** [comment]
Hello, wanted to know how the solution to the problem. (Google translate:) )

**Comment by DarkCloud14** [comment]
Hey I didn't get the time yet to recompile StyleCop and MonoDevelop.StyleCop with .Net 4.5 and check if that fixes the problem. Will try to do this by the end of this week.

**Comment by DarkCloud14** [comment]
I've tested it with a rebuild version of StyleCop using .Net Framework 4.5 and it works again.
I should get a build done this week in case the build bot works, if not I'll build it manually and upload it on GitHub.

**Comment by MazZilaaaa** [comment]
Great
