### ISSUE TITLE
StyleCop for Xamarin studio error.

### ISSUE THREAD

**Issue by MazZilaaaa** [DarkCloud14/MonoDevelop.StyleCop#13]
Hello. After update xamarin studio to 
=== Xamarin Studio ===

Version 5.9 (build 431)
Installation UUID: f20cbded-52f6-47ea-b225-7288a535cddb
Runtime:
	Mono 4.0.0 ((detached/d136b79)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 400000143

=== Apple Developer Tools ===

Xcode 6.3.1 (7703)
Build 6D1002

=== Xamarin.iOS ===

Version: 8.10.0.267 (Business Edition)
Hash: 6481535
Branch: master
Build date: 2015-04-27 04:38:13-0400

=== Xamarin.Android ===

Not Installed

=== Xamarin Android Player ===

Not Installed

=== Xamarin.Mac ===

Not Installed

=== Build Information ===

Release ID: 509000431
Git revision: 7560726734fc7267de2fa9abed2509968deefaa8
Build date: 2015-04-17 19:25:48-04
Xamarin addins: 2e772c734ab3148054eae7bf8949f340fdeb5e5e

=== Operating System ===

Mac OS X 10.10.2
Darwin Fadeev-iMac.local 14.1.0 Darwin Kernel Version 14.1.0
    Thu Feb 26 19:26:47 PST 2015
    root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64

Run Stylecop not working with error SA0001: CoreParser: An exception occurred while parsing the file: System.TypeLoadException, A type load exception has occurred.

**Comment by soneyworld** [comment]
Hi! Is there a solution for this problem?

**Comment by DarkCloud14** [comment]
Yeah get the updated version of MonoDevelop.StyleCop for MD 5.7 and higher, this will fix the problem.
http://addins.monodevelop.com/Project/Index/54
