### ISSUE TITLE
Installation failed: could not read add-in description

### ISSUE THREAD

**Issue by Mailaender** [DarkCloud14/MonoDevelop.StyleCop#15]
Trying to update StyleCop support to version 1.0.1.9 fails with MonoDevelop 5.9.5

![image](https://cloud.githubusercontent.com/assets/756669/11450688/7f01d434-95a9-11e5-8a7e-4190ffb8c894.png)

:cry:

**Comment by DarkCloud14** [comment]
Sorry for my late response, did you try to install it from file or from Xamarins addin server?
Also did you try MonoDevelop or Xamarin Studio?
Tested it with Xamarin Studio v5.10 now and it works fine.

**Comment by Mailaender** [comment]
I am on Linux and this was done via the AddIn servers. Can't check 5.10 as it won't compile due to the tarball being incomplete (NuGet restore won't work on secure isolated VMs without internet access): https://build.opensuse.org/package/show/home:Mailaender:branches:Mono:Factory/monodevelop

**Comment by DarkCloud14** [comment]
Stupid question but did you try to download the addin package and install that instead?
If not can you try to download it from the following link and test if that works.
http://addins.monodevelop.com/Project/Index/54

The package for v5.7 (it's 5.7 and up..)

**Comment by Mailaender** [comment]
Did you unpublish version 1.0.1.9? Because it seems to be gone now.

**Comment by DarkCloud14** [comment]
Uhm I never published v1.0.1.9 thought it was a typo and you meant v1.0.1.8.
The last official release was v1.0.1.8, see the GitHub release page.

**Comment by Mailaender** [comment]
Weird, it seems to be up-to-date now. Not sure what happened there. Sorry for bothering you.
