### ISSUE TITLE
Doesn't work with Xamarin Studio 6?

### ISSUE THREAD

**Issue by jhafer** [DarkCloud14/MonoDevelop.StyleCop#16]
We're playing with the alpha version of Xamarin Studio 6. Are there plans to have this plugin work with that version?

**Comment by DarkCloud14** [comment]
Hi,
didn't work on it for a long time now but I'll take a look at this.

**Comment by kenkyee** [comment]
+1 tried out the latest beta of xamarin studio 6 and noticed the same issue :-(

**Comment by hex** [comment]
What's the status on this? Did anyone managed to get it working?

**Comment by fkubista** [comment]
Any update, Xamarin Studio 6.0 is now in the stable channel.

**Comment by DarkCloud14** [comment]
Sorry have already done updates on the code and had it working but the buildbot didn't work properly for all build versions.

If you want you can temporarily try to build a custom package by executing ./configure.sh script and then use

make all

to build a package that you than should be able to install if it builds without errors.

**Comment by mobrien650** [comment]
Installing the add-on after building with configure.sh and make all worked for me for Xamarin Studio 6.0 on OS X. Thanks.

**Comment by DarkCloud14** [comment]
Ok a new version is build and should be available via MonoDevelop/Xamarin Studio soon.
This release also contains the latest StyleCop v4.7.54.
If you can't wait I've uploaded the new version on GitHub too..

**Comment by kenkyee** [comment]
Thanks :-)
