### ISSUE TITLE
Current release doesn't support C# 6 features

### ISSUE THREAD

**Issue by sbergen** [DarkCloud14/MonoDevelop.StyleCop#17]
The current release (1.0.1.8) doesn't support C# 6 features, while as far as I gathered, the latest StyleCop does.

I was unable to successfully build master on OS X (ran into several issues there), so I don't know if everything is up to date there. However, it would be great if a new release was made that has the latest version of StyleCop, including C# 6 support.

**Comment by DarkCloud14** [comment]
A new version is build and should be available via MonoDevelop/Xamarin Studio soon.
This release also contains the latest StyleCop v4.7.54 and so it should contain C# 6 support.
If you can't wait I've also uploaded the new version on GitHub.
