### ISSUE TITLE
Settings on solution level

### ISSUE THREAD

**Issue by Mizipzor** [DarkCloud14/MonoDevelop.StyleCop#18]
I can right click a project and change the settings for that project and the settings file is placed right next to the project file. But that file could be moved to be right next to the solution file, and if I run StyleCop on the solution the settings appear to be picked up. Yet, I cant right click the solution to edit settings. Why?

**Comment by DarkCloud14** [comment]
That's the way it was integrated in the StyleCop addin for Visual Studio.
As at the moment I call the settings dialog of StyleCop itself I'm not sure if that supports opening the settings dialog on solution level.
I could test it but as I have to implement a GTK# based settings dialog for StyleCop settings which integrate better into MonoDevelop, I can try to add this possibility there.

Don't ask me when this will be done as I can't answer that. I don't have much time at the moment to work on this..

**Comment by Mizipzor** [comment]
Our (Unity) project uses both Visual Studio and MonoDeveloper. I used MonoDeveloper to create the setting file, but then I moved it to the solution folder and its correctly picked up by both.

**Comment by DarkCloud14** [comment]
Yes StyleCop itself picks it up correctly but I never tested if the settings window implementation will do that too..

**Comment by Mizipzor** [comment]
It does not. If I open the settings window I get default settings. And if I save a settings file is created right next to the project file. I would be interested in trying to fix this myself. Any hints on where I could start? :)

**Comment by DarkCloud14** [comment]
I'll take a look at it tomorrow and give you some feedback.

**Comment by DarkCloud14** [comment]
Ok just looked at the code again and it looks like it'll work if done correctly as you give the StyleCop settings dialog function call a settings file path as parameter.

You may take a look at the class StyleCopSettingsCommandHandler in CommandHandler directory.

**Comment by DarkCloud14** [comment]
Will be fixed with #4.
