### ISSUE TITLE
Crash (bad access) opening settings

### ISSUE THREAD

**Issue by mr-fixit** [DarkCloud14/MonoDevelop.StyleCop#20]
I installed StyleCop Support v. 1.0.1.9,  via the Add-in Manager in Xamarin Studio Community v 6.2.0.1821.

I right-click on either my Android or iOS targets, and choose 'StyleCop Settings'.

After a few seconds, Xamarin Studio crashes.

[StyleCop Crash.txt](https://github.com/DarkCloud14/MonoDevelop.StyleCop/files/879355/StyleCop.Crash.txt)

**Comment by mr-fixit** [comment]
Could be a different manifestation of #14, which means I'm joining the queue of people interested in #4

**Comment by DarkCloud14** [comment]
Sorry for my late response I wasn't working on the project for some time but will invest a bit more time now again to get issue #4 done.

Unfortunately I can't really say if it's a different manifestation of #14 but if Xamarin Studio 6.2.0 is already running as 64bit process I would bet it is as 64bit mono doesn't bring the necessary carbon driver to do the Windows.Forms drawing stuff.

I will close this issue for now and mark it as duplicate, should there be crashes in a future release where I finally fixed #4 you can create a new issue.
