### ISSUE TITLE
Visual Studio for mac support

### ISSUE THREAD

**Issue by flashfoxter** [DarkCloud14/MonoDevelop.StyleCop#21]
Visual Studio for mac officially release, it means Xamarin Studio deprecated now, how we can use this addin for Visual Studio for mac ? Maybe ideas about temp workarounds.

**Comment by DarkCloud14** [comment]
Made several changes to support Visual Studio for Mac.
Using the tag 1.0.1.9-VisualStudio or the current master code should allow you to build a version for it.

You can also wait until MDs buildbot build a version and I can publish it so you can download it via Extension manager..
Not sure how long it'll take until the buildbot build the version, currently waiting for it to start..

**Comment by DarkCloud14** [comment]
Ok I just uploaded a package for VS for Mac here at GitHub.
It's the MonoDevelop.StyleCop-1.0.1.9_MD7.0.mpack of the 1.0.1.9 release, VS for Mac is MD7.0..
https://github.com/DarkCloud14/MonoDevelop.StyleCop/releases/download/1.0.1.9/MonoDevelop.StyleCop-1.0.1.9_MD7.0.mpack
