### ISSUE TITLE
Command Line Support

### ISSUE THREAD

**Issue by cosminstirbu** [DarkCloud14/MonoDevelop.StyleCop#23]
Hello,

I have installed MoboDevelop.StyleCop 1.0.1.9 with Visual Studio For Mac 7.1.
I'm interested in integrating StyleCop as part of my automated build in Jenkins but it is unclear how I can run StyleCop from command line.

Any help would be appreciated.

Thank you.

**Comment by DarkCloud14** [comment]
Hi,

I'm sorry but this won't be possible with this MonoDevelop plugin but there is a NuGet package that might help you out. Checkout this https://www.nuget.org/packages/StyleCop.MSBuild

Hope this will help you.

**Comment by cosminstirbu** [comment]
Thank you for your answer.

I was able to use https://www.nuget.org/packages/StyleCop.MSBuild that integrates StyleCop in the build process and outputs an .xml file with the warnings. I've integrated that in Jenkins, only that unfortunately the Violations plugin that has StyleCop support also has a bug that doesn't really allow  navigation to the source file (since it hasn't been maintained since 2015).

Still, it does the job so thank you for your help!

**Comment by DarkCloud14** [comment]
If you're talking about the Jenkins plugin you might checkout this one:
https://github.com/jenkinsci/warnings-plugin

Not sure how far this one is or if it's any better, just found a reference to this in a issue where they discussed the future of the violations-plugin and someone referenced this plugin: https://github.com/jenkinsci/violations-plugin/tree/violations-lib but in Jenkins wiki it says that this one isn't maintained anymore and a link to the above warnings-plugin.

I didn't try any of these plugins so I don't know if they work better or not but at least they should support StyleCop violations according to the wikis..

**Comment by cosminstirbu** [comment]
It's funny that I've been using https://github.com/jenkinsci/warnings-plugin on a separate Android native project for a long time, and it never occurred to me that it might have support for StyleCop as well.

When I performed a quick Google search it didn't pop up as it would support it. I'll have look, it might just work as expected.

I'll have a look and get back to you. Thank you!

**Comment by cosminstirbu** [comment]
It works exactly as I expected, it's exactly what I need. Thank you for suggesting using it.

**Comment by DarkCloud14** [comment]
You're welcome, I'm glad that I could help and that the suggestion worked!
