### ISSUE TITLE
Clicking "StyleCop Settings" crashes Visual Studio for Mac

### ISSUE THREAD

**Issue by TomSoderling** [DarkCloud14/MonoDevelop.StyleCop#24]
I've installed the addin for VS for Mac, but when I click on the "StyleCop Settings" menu option (displayed by right-clicking on a project) Visual Studio stops responding and crashes a few seconds later.

Addin: MonoDevelop.StyleCop-1.0.1.9_MD7.0.mpack
VS for Mac: Version 7.1 (build 1297)

**Comment by DarkCloud14** [comment]
Sorry this is a known issue and will be fixed as soon as I fix issue #4.
I didn't have much time in the last years and the GUI integration is not so well documented and
I already had several problems that I had to find workarounds or had to look in the source code of monodevelop (VS for Mac is based on that) to figure out how they're doing stuff..

I can't fix the error you get now as this is a problem of Mono as they don't have a renderer for System.Windows.Forms GUI elements anymore in the 64bit version and VS for Mac runs as 64bit.

At the moment you're unfortunately out of luck editing the settings, sorry.
I'm already working on the GUI integration but also have to make adjustments on the original StyleCop project as not all settings are accessible from outside and so I would have to use reflection to get the things I need..

**Comment by TomSoderling** [comment]
Okay. No big deal. I just realized I can edit the rules file by hand

**Comment by Praeire** [comment]
> Okay. No big deal. I just realized I can edit the rules file by hand
Can you write instruction how to edit rules directly?

**Comment by DarkCloud14** [comment]
The new version with GTK settings is finally done and can be downloaded at the releases page of the project at GitHub. Unfortunately the addin page of MonoDevelop doesn't work correctly anymore and so I can't update the version there that it's automatically published to everybody who uses MonoDevelop addin update mechanism.

You must download the appropriate package and install it manually via install file in addin manager.

**Comment by cosminstirbu** [comment]
Thank you for this release!
