### ISSUE TITLE
Better integration of StyleCops configuration window.

### ISSUE THREAD

**Issue by DarkCloud14** [DarkCloud14/MonoDevelop.StyleCop#4]
At the moment StyleCop settings are configured with StyleCops integrated settings editor.
As this is based on System.Windows.Forms Framework it is necessary that OSX users install X11 first.
A better way to handle this is to integrate the settings editor into MonoDevelops project settings using GTK#.
That way X11 shouldn't be necessary anymore on OSX.

**Comment by cosminstirbu** [comment]
Hello,

First of all thank you for your work on this project.
I'm also having issues opening the settings editor so I'd really appreciate having this issue fixed.

Thank you

**Comment by DarkCloud14** [comment]
Ok I didn't work on the project for a long time now but I recently started to work on project again to get this issue finally finished. I can't tell you a date yet but at least I can let you know that I'm working on it again.

**Comment by DarkCloud14** [comment]
The new version with GTK settings is finally done and can be downloaded at the releases page of the project at GitHub. Unfortunately the addin page of MonoDevelop doesn't work correctly anymore and so I can't update the version there that it's automatically published to everybody who uses MonoDevelop addin update mechanism.

You must download the appropriate package and install it manually via install file in addin manager.
